a = int(input("Enter the value of a:"))
b = int(input("Enter the value b :"))
print("The value of", a, "+", b, "is :", a+b) 
print("The value of", a, "*", b, "is :", a*b) 
print("The value of", a, "-", b, "is :", a-b)
print("The value of", a, "/", b, "is :", a/b) 
print("The value of", a, "//", b, "is :", a//b) 
print("The value of", a, "%", b, "is :", a%b) 
print("The value of", a, "**", b, "is :", a**b) 
